<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ms info</name>
   <tag></tag>
   <elementGuidId>05decb4c-5793-4321-8533-7117a2a14faf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layout']/div[2]/main/div/div/div/div[2]/div/div/div/div/section[2]/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4a6306d3-26ac-4f04-8794-35a6f1ef8f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>
      undefined
      button_base__L57y3
      button_contained__HHfv_
      button_medium__VxgiQ
      undefined
      button_maxWidth__I571k
      button__body1__tIrcS
      __press
    </value>
      <webElementGuid>e6e1924c-3fea-4ed5-a322-dd4548f914a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/alarmas-para-casa/pisos</value>
      <webElementGuid>ca38ab58-0800-4a44-9d05-773600306486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Más info</value>
      <webElementGuid>178589aa-1c57-4d4e-9779-7d0005696214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout&quot;)/div[@class=&quot;app_body__A7L1d&quot;]/main[1]/div[@class=&quot;index_container__KNQ8V __popPage&quot;]/div[@class=&quot;product-card-group_container__lBG7y&quot;]/div[@class=&quot;container_container__NjHmW&quot;]/div[@class=&quot;product-card-group_products__OT5dD&quot;]/div[@class=&quot;product-card-group_desktop__VJyVy&quot;]/div[@class=&quot;product-card-group_product_container__vAY_4&quot;]/div[@class=&quot;product-card_container__XZSQJ&quot;]/div[@class=&quot;product-card_content__oFA_P 
        undefined&quot;]/section[2]/div[@class=&quot;product-card_button_container__Qw24K&quot;]/a[@class=&quot;undefined
      button_base__L57y3
      button_contained__HHfv_
      button_medium__VxgiQ
      undefined
      button_maxWidth__I571k
      button__body1__tIrcS
      __press&quot;]</value>
      <webElementGuid>c171cb73-7a4d-4805-8500-419168da9589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4440a496-aac7-4944-aa51-3bdc74c7bd2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>
      undefined
      button_base__L57y3
      button_contained__HHfv_
      button_medium__VxgiQ
      undefined
      button_maxWidth__I571k
      button__body1__tIrcS
      __press
    </value>
      <webElementGuid>4ac2393c-c77d-4777-bc0a-bad78941674c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/alarmas-para-casa/pisos</value>
      <webElementGuid>98438d62-dcf5-4bd8-b7c8-b2eaf4e3ac0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Más info</value>
      <webElementGuid>84ec7aee-369e-4baf-b952-02347c499eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout&quot;)/div[@class=&quot;app_body__A7L1d&quot;]/main[1]/div[@class=&quot;index_container__KNQ8V __popPage&quot;]/div[@class=&quot;product-card-group_container__lBG7y&quot;]/div[@class=&quot;container_container__NjHmW&quot;]/div[@class=&quot;product-card-group_products__OT5dD&quot;]/div[@class=&quot;product-card-group_desktop__VJyVy&quot;]/div[@class=&quot;product-card-group_product_container__vAY_4&quot;]/div[@class=&quot;product-card_container__XZSQJ&quot;]/div[@class=&quot;product-card_content__oFA_P 
        undefined&quot;]/section[2]/div[@class=&quot;product-card_button_container__Qw24K&quot;]/a[@class=&quot;undefined
      button_base__L57y3
      button_contained__HHfv_
      button_medium__VxgiQ
      undefined
      button_maxWidth__I571k
      button__body1__tIrcS
      __press&quot;]</value>
      <webElementGuid>6b605d8e-f875-40a5-a1b1-09727eadd459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8beb55f8-f60b-475c-aed4-a7eb44ca529e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>
      undefined
      button_base__L57y3
      button_contained__HHfv_
      button_medium__VxgiQ
      undefined
      button_maxWidth__I571k
      button__body1__tIrcS
      __press
    </value>
      <webElementGuid>2f7aacaa-4681-4e94-8527-9452583fa695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/alarmas-para-casa/pisos</value>
      <webElementGuid>96f332bf-a4ac-4df6-8e0e-64060ee2c307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Más info</value>
      <webElementGuid>d1074536-832c-4bae-8bb5-ee8e62917e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout&quot;)/div[@class=&quot;app_body__A7L1d&quot;]/main[1]/div[@class=&quot;index_container__KNQ8V __popPage&quot;]/div[@class=&quot;product-card-group_container__lBG7y&quot;]/div[@class=&quot;container_container__NjHmW&quot;]/div[@class=&quot;product-card-group_products__OT5dD&quot;]/div[@class=&quot;product-card-group_desktop__VJyVy&quot;]/div[@class=&quot;product-card-group_product_container__vAY_4&quot;]/div[@class=&quot;product-card_container__XZSQJ&quot;]/div[@class=&quot;product-card_content__oFA_P 
        undefined&quot;]/section[2]/div[@class=&quot;product-card_button_container__Qw24K&quot;]/a[@class=&quot;undefined
      button_base__L57y3
      button_contained__HHfv_
      button_medium__VxgiQ
      undefined
      button_maxWidth__I571k
      button__body1__tIrcS
      __press&quot;]</value>
      <webElementGuid>afc05eb6-0ecd-4c4d-bda4-ef841bd227a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout']/div[2]/main/div/div/div/div[2]/div/div/div/div/section[2]/div[2]/a</value>
      <webElementGuid>98f29e87-732c-47b0-9b27-8e3de2ab8330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Más info')]</value>
      <webElementGuid>6ec50096-bd62-42bb-9430-49ad3775a656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Placa disuasoria'])[1]/following::a[1]</value>
      <webElementGuid>6e6c92fa-675c-408d-8098-4855bbadcbfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Teclado + Sirena'])[1]/following::a[1]</value>
      <webElementGuid>a1f7d740-3144-429a-924e-6f197e5f92d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Tienes dudas?'])[1]/preceding::a[1]</value>
      <webElementGuid>87413b2c-6905-4b41-a666-33301bbcdd52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Te llamamos'])[2]/preceding::a[1]</value>
      <webElementGuid>c19b53e8-3ec8-4fbd-9964-e4f3a901f5f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Más info']/parent::*</value>
      <webElementGuid>02bfeedb-9e29-46ec-a614-b7895fedf3cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/alarmas-para-casa/pisos')])[2]</value>
      <webElementGuid>56cd6d7e-0d81-47c0-99b8-56ee75aaa6c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>296ea803-79a5-49e6-a4e4-d26d5753ad54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/alarmas-para-casa/pisos' and (text() = 'Más info' or . = 'Más info')]</value>
      <webElementGuid>3f04b068-7b45-46fe-8313-e2a17617eead</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
