<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lo quiero</name>
   <tag></tag>
   <elementGuidId>5f55ff81-2e6b-4f37-bd3f-762f625ffd57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layout']/div[2]/main/div/section/div/div/div/div/div[2]/section[2]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>22a9b3d1-44c1-440e-99fa-523a87e66253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>
      undefined
      button_base__L57y3
      button_contained__HHfv_
      button_medium__VxgiQ
      undefined
      button_maxWidth__I571k
      button__body1__tIrcS
      __press
    </value>
      <webElementGuid>58270c08-c8cb-404e-bd39-1f8cfa6828d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/checkout</value>
      <webElementGuid>e96b2dd1-de6f-452b-94a7-b3ef96341c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lo quiero</value>
      <webElementGuid>59954151-7418-4249-8db9-9dbd35600b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout&quot;)/div[@class=&quot;app_body__A7L1d&quot;]/main[1]/div[@class=&quot;__popPage&quot;]/section[@class=&quot;productos_page_container__uEsQF&quot;]/div[@class=&quot;product-selector_container__dUUim&quot;]/div[@class=&quot;product-selector_product___NqXm&quot;]/div[@class=&quot;product-card-images_container__i6_ri
    undefined&quot;]/div[@class=&quot;product-card-images_price__CVk30&quot;]/div[@class=&quot;price-box_container__lXnA7
      price-box_break_on_tablet__guSOU&quot;]/section[@class=&quot;price-box_lower__5RjXK&quot;]/div[@class=&quot;price-box_button__ddAl0&quot;]/a[@class=&quot;undefined
      button_base__L57y3
      button_contained__HHfv_
      button_medium__VxgiQ
      undefined
      button_maxWidth__I571k
      button__body1__tIrcS
      __press&quot;]</value>
      <webElementGuid>4727d56e-62da-4ff3-9a8d-64fa864798ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bc4463fc-1c2a-46e8-acb3-d01bd6cd9617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>
      undefined
      button_base__L57y3
      button_contained__HHfv_
      button_medium__VxgiQ
      undefined
      button_maxWidth__I571k
      button__body1__tIrcS
      __press
    </value>
      <webElementGuid>b4e9e715-6c59-4e79-b427-79a3f223e81e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/checkout</value>
      <webElementGuid>be545bff-52dd-4647-9e18-11026ec1092a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lo quiero</value>
      <webElementGuid>bc4996be-3ebb-4cd6-bfd7-d3b9193ae832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout&quot;)/div[@class=&quot;app_body__A7L1d&quot;]/main[1]/div[@class=&quot;__popPage&quot;]/section[@class=&quot;productos_page_container__uEsQF&quot;]/div[@class=&quot;product-selector_container__dUUim&quot;]/div[@class=&quot;product-selector_product___NqXm&quot;]/div[@class=&quot;product-card-images_container__i6_ri
    undefined&quot;]/div[@class=&quot;product-card-images_price__CVk30&quot;]/div[@class=&quot;price-box_container__lXnA7
      price-box_break_on_tablet__guSOU&quot;]/section[@class=&quot;price-box_lower__5RjXK&quot;]/div[@class=&quot;price-box_button__ddAl0&quot;]/a[@class=&quot;undefined
      button_base__L57y3
      button_contained__HHfv_
      button_medium__VxgiQ
      undefined
      button_maxWidth__I571k
      button__body1__tIrcS
      __press&quot;]</value>
      <webElementGuid>25892a39-ec12-45ea-86f0-1f0db92c0f69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout']/div[2]/main/div/section/div/div/div/div/div[2]/section[2]/div/a</value>
      <webElementGuid>7f2228d2-56d4-4ec7-87c5-121520bd93fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Lo quiero')]</value>
      <webElementGuid>d925b607-ba07-45da-b0a3-6ac80a0aeeab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('', &quot;'&quot;, '90 €/mes')])[1]/following::a[1]</value>
      <webElementGuid>d7598222-50e4-4e32-b084-dff608668de9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Te interesa?'])[1]/following::a[1]</value>
      <webElementGuid>0799a62a-0e7c-486b-b6a8-423a6be482bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Tienes dudas?'])[1]/preceding::a[1]</value>
      <webElementGuid>61dfef66-002b-44a9-8d35-4631c4ff912d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Te llamamos gratis y las resolvemos'])[1]/preceding::a[1]</value>
      <webElementGuid>f7e806db-dbcd-4ea5-80f5-93b0724b652e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lo quiero']/parent::*</value>
      <webElementGuid>9816005f-9537-4a29-bf54-35bd4f253616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/checkout')]</value>
      <webElementGuid>b168e80a-8dc1-4406-9989-24aca29fe8db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/a</value>
      <webElementGuid>5dec4320-db01-4ea6-b533-9a9b472e2c55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/checkout' and (text() = 'Lo quiero' or . = 'Lo quiero')]</value>
      <webElementGuid>e9784169-3205-4128-8030-ac4af90b21c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
