<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_No soy clienteAn no eres cliente Yoigo</name>
   <tag></tag>
   <elementGuidId>f5744f4e-f314-4efa-b373-77e462b50897</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layout']/div[2]/main/div/section/div/div/div/div/div/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.client-select_not_selected__6_vHR</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dea17b66-9ef0-4fa7-8181-6b4f47d3e304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>client-select_not_selected__6_vHR</value>
      <webElementGuid>c530b3b1-0046-4924-a762-036f50108721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No soy clienteAún no eres cliente Yoigo</value>
      <webElementGuid>6a96859c-b18d-40ca-95ec-d45485ca2902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout&quot;)/div[@class=&quot;app_body__A7L1d&quot;]/main[1]/div[@class=&quot;__popPage&quot;]/section[@class=&quot;productos_page_container__uEsQF&quot;]/div[@class=&quot;product-selector_container__dUUim&quot;]/div[@class=&quot;product-selector_product___NqXm&quot;]/div[@class=&quot;product-card-images_container__i6_ri
    undefined&quot;]/div[@class=&quot;product-card-images_price__CVk30&quot;]/div[@class=&quot;client-select_container__F2Xsi&quot;]/button[@class=&quot;client-select_not_selected__6_vHR&quot;]</value>
      <webElementGuid>470e7323-3a77-438f-9b3d-7d14aae2c5b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>979c64a9-a28a-4454-a2b4-bc51cb56f27d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>client-select_not_selected__6_vHR</value>
      <webElementGuid>eff87484-d834-468f-8df7-593fefdd40ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No soy clienteAún no eres cliente Yoigo</value>
      <webElementGuid>c37bb381-f39a-4f84-831f-d733e0a2a697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout&quot;)/div[@class=&quot;app_body__A7L1d&quot;]/main[1]/div[@class=&quot;__popPage&quot;]/section[@class=&quot;productos_page_container__uEsQF&quot;]/div[@class=&quot;product-selector_container__dUUim&quot;]/div[@class=&quot;product-selector_product___NqXm&quot;]/div[@class=&quot;product-card-images_container__i6_ri
    undefined&quot;]/div[@class=&quot;product-card-images_price__CVk30&quot;]/div[@class=&quot;client-select_container__F2Xsi&quot;]/button[@class=&quot;client-select_not_selected__6_vHR&quot;]</value>
      <webElementGuid>10c124a3-bbd2-4ad7-89f7-04b48258cd07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout']/div[2]/main/div/section/div/div/div/div/div/button[2]</value>
      <webElementGuid>f1111ba9-6783-4e99-b0ee-1ccf4978302c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disfruta de las ventajas de ser cliente Yoigo'])[1]/following::button[1]</value>
      <webElementGuid>fbd56e75-d908-492e-b399-d495887fba08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Te interesa?'])[1]/preceding::button[1]</value>
      <webElementGuid>1e73b273-b28b-412a-a2aa-1e5309c410bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='No soy cliente']/parent::*</value>
      <webElementGuid>81ccdfad-7e3f-4e9a-a8fe-15c25a03371b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>ab542ac1-034b-43dd-9619-6e3418960719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'No soy clienteAún no eres cliente Yoigo' or . = 'No soy clienteAún no eres cliente Yoigo')]</value>
      <webElementGuid>8f157950-a388-4431-abf3-3245b655e8fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
