<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Confirmar el pedido</name>
   <tag></tag>
   <elementGuidId>9556b5a1-8e21-4873-b746-fc167b81c5c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='checkout-step-header-3']/div[2]/section/form/div[10]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>93393cd5-bc83-468d-8eef-14d853f24ecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>
      undefined
      button_base__L57y3
      button_contained__HHfv_
      button_medium__VxgiQ
      undefined
      undefined
      button__body1__tIrcS
      __press
    </value>
      <webElementGuid>e044d69e-e596-4243-a64d-df483c626260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirmar el pedido</value>
      <webElementGuid>15767e94-009f-4f18-95fd-52a0ac9bf57f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout-step-header-3&quot;)/div[@class=&quot;checkout-step_body__EMYJI&quot;]/section[@class=&quot;checkout-steps_form_3__g0OXI&quot;]/form[@class=&quot;form_form__DAL4d&quot;]/div[@class=&quot;jsx-2252237956&quot;]/div[@class=&quot;checkout-steps_button_container__126M6 checkout-steps_submit2__YmDxd&quot;]/button[@class=&quot;undefined
      button_base__L57y3
      button_contained__HHfv_
      button_medium__VxgiQ
      undefined
      undefined
      button__body1__tIrcS
      __press&quot;]</value>
      <webElementGuid>4d9f4608-5cea-427c-bd1d-224adcf91163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>12481568-fdef-4c7d-95c8-fd0dc1abb707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>
      undefined
      button_base__L57y3
      button_contained__HHfv_
      button_medium__VxgiQ
      undefined
      undefined
      button__body1__tIrcS
      __press
    </value>
      <webElementGuid>199985ab-14e0-4152-a8bb-ca5e3d9440fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirmar el pedido</value>
      <webElementGuid>3f404042-c762-4f79-be73-12a3629155a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout-step-header-3&quot;)/div[@class=&quot;checkout-step_body__EMYJI&quot;]/section[@class=&quot;checkout-steps_form_3__g0OXI&quot;]/form[@class=&quot;form_form__DAL4d&quot;]/div[@class=&quot;jsx-2252237956&quot;]/div[@class=&quot;checkout-steps_button_container__126M6 checkout-steps_submit2__YmDxd&quot;]/button[@class=&quot;undefined
      button_base__L57y3
      button_contained__HHfv_
      button_medium__VxgiQ
      undefined
      undefined
      button__body1__tIrcS
      __press&quot;]</value>
      <webElementGuid>d7cec0da-a4e9-473b-82a3-665d9a8ef355</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-step-header-3']/div[2]/section/form/div[10]/div/button</value>
      <webElementGuid>a64fefc6-bed3-4233-bbce-7683e103bb8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Condiciones Generales de Contratación'])[1]/following::button[1]</value>
      <webElementGuid>48f321f5-ce27-4eff-b91d-860a93855b90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Código promocional'])[1]/following::button[1]</value>
      <webElementGuid>3d04660c-0947-4363-a1d3-ec4121a326d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nuestras alarmas'])[1]/preceding::button[1]</value>
      <webElementGuid>c84e93e1-42f1-4909-a7f3-fac950dc858c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Conoce nuestra alarma'])[3]/preceding::button[1]</value>
      <webElementGuid>40101c90-3905-44d5-9a20-3180d59f9a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirmar el pedido']/parent::*</value>
      <webElementGuid>10b8cccb-ace3-43c7-abf5-17e029c9ff85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/button</value>
      <webElementGuid>b57e5cf9-0467-4a82-84e4-6476fbd0f726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Confirmar el pedido' or . = 'Confirmar el pedido')]</value>
      <webElementGuid>5d333227-ef03-4b22-835f-58f563631150</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
