<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continuar</name>
   <tag></tag>
   <elementGuidId>3f6e758c-4669-4d50-8b13-0bf5255d9cb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='checkout-step-header-2']/div[2]/section/form/div[12]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4832b2d5-1a5c-4aa9-9f89-e5dc026ce5fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>
      undefined
      button_base__L57y3
      button_contained__HHfv_
      button_medium__VxgiQ
      undefined
      undefined
      button__body1__tIrcS
      __press
    </value>
      <webElementGuid>dce4c25a-c528-41ea-818f-8a9216e5ac67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continuar</value>
      <webElementGuid>a5822b6c-2c0d-42c8-a99c-6272ab8bd2e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout-step-header-2&quot;)/div[@class=&quot;checkout-step_body__EMYJI&quot;]/section[@class=&quot;checkout-steps_form_2__d1nZe&quot;]/form[@class=&quot;form_form__DAL4d&quot;]/div[@class=&quot;jsx-2252237956&quot;]/div[@class=&quot;checkout-steps_button_container__126M6 checkout-steps_submit2__YmDxd&quot;]/button[@class=&quot;undefined
      button_base__L57y3
      button_contained__HHfv_
      button_medium__VxgiQ
      undefined
      undefined
      button__body1__tIrcS
      __press&quot;]</value>
      <webElementGuid>1259e368-45e1-44f6-8980-381e543d6cb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>80d53ef4-ec24-465a-9e88-6f32c155db8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>
      undefined
      button_base__L57y3
      button_contained__HHfv_
      button_medium__VxgiQ
      undefined
      undefined
      button__body1__tIrcS
      __press
    </value>
      <webElementGuid>cc095f4e-96aa-4c0a-8678-02165e7a95f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continuar</value>
      <webElementGuid>7ab4695b-f6d6-4ee3-95a0-2eded690bb46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout-step-header-2&quot;)/div[@class=&quot;checkout-step_body__EMYJI&quot;]/section[@class=&quot;checkout-steps_form_2__d1nZe&quot;]/form[@class=&quot;form_form__DAL4d&quot;]/div[@class=&quot;jsx-2252237956&quot;]/div[@class=&quot;checkout-steps_button_container__126M6 checkout-steps_submit2__YmDxd&quot;]/button[@class=&quot;undefined
      button_base__L57y3
      button_contained__HHfv_
      button_medium__VxgiQ
      undefined
      undefined
      button__body1__tIrcS
      __press&quot;]</value>
      <webElementGuid>4119b4b0-98d2-41c0-90c7-8e6090d8ebaf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-step-header-2']/div[2]/section/form/div[12]/div/button</value>
      <webElementGuid>99215ea0-d337-4595-99b6-213dcad2f55e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número'])[1]/following::button[1]</value>
      <webElementGuid>edea014f-21f8-4219-889e-368937143f0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nombre de la vía'])[1]/following::button[1]</value>
      <webElementGuid>c2f72778-5e7e-4744-b9ec-006d8b9cf3ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datos de pago y confirmación'])[1]/preceding::button[1]</value>
      <webElementGuid>a96426c8-afc3-4699-b7ad-993147eaba60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nuestras alarmas'])[1]/preceding::button[1]</value>
      <webElementGuid>86b003a8-02d7-4414-84a0-76dd50ae180a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continuar']/parent::*</value>
      <webElementGuid>1a480536-9992-4759-9a56-387c07993114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/button</value>
      <webElementGuid>11625e86-0f2d-4a58-92e9-a7298da0d57c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Continuar' or . = 'Continuar')]</value>
      <webElementGuid>0ee8dcd9-2326-4977-9752-e02e1a83b661</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
