<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Confirmar</name>
   <tag></tag>
   <elementGuidId>7b95a83c-35a8-4715-a81a-e3af28d8946a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='checkout-step-header-1']/div[2]/section/form/div[5]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d5d7de68-1fe3-46a6-be97-1de2c263884c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>
      undefined
      button_base__L57y3
      button_contained__HHfv_
      button_medium__VxgiQ
      undefined
      undefined
      button__body1__tIrcS
      __press
    </value>
      <webElementGuid>5585c736-98ef-46a7-95bf-558fedce4387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirmar</value>
      <webElementGuid>f8a95fec-6529-45d7-bc15-3cc34bd1a38b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout-step-header-1&quot;)/div[@class=&quot;checkout-step_body__EMYJI&quot;]/section[@class=&quot;checkout-steps_form_1__RQPYl&quot;]/form[@class=&quot;form_form__DAL4d&quot;]/div[@class=&quot;jsx-2252237956&quot;]/div[@class=&quot;checkout-steps_button_container__126M6 checkout-steps_submit1__6G9ph&quot;]/button[@class=&quot;undefined
      button_base__L57y3
      button_contained__HHfv_
      button_medium__VxgiQ
      undefined
      undefined
      button__body1__tIrcS
      __press&quot;]</value>
      <webElementGuid>8774a765-0a1a-4ff2-99e8-b4b22043b4f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>37cb1a31-4137-41b4-a8db-c9a4207665af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>
      undefined
      button_base__L57y3
      button_contained__HHfv_
      button_medium__VxgiQ
      undefined
      undefined
      button__body1__tIrcS
      __press
    </value>
      <webElementGuid>65515bf7-3758-4ce0-bea3-0ea43315882d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirmar</value>
      <webElementGuid>d76af295-846a-499b-becb-4002606c2deb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout-step-header-1&quot;)/div[@class=&quot;checkout-step_body__EMYJI&quot;]/section[@class=&quot;checkout-steps_form_1__RQPYl&quot;]/form[@class=&quot;form_form__DAL4d&quot;]/div[@class=&quot;jsx-2252237956&quot;]/div[@class=&quot;checkout-steps_button_container__126M6 checkout-steps_submit1__6G9ph&quot;]/button[@class=&quot;undefined
      button_base__L57y3
      button_contained__HHfv_
      button_medium__VxgiQ
      undefined
      undefined
      button__body1__tIrcS
      __press&quot;]</value>
      <webElementGuid>db3c524b-ef0a-4aea-9aac-18d18a7f9824</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-step-header-1']/div[2]/section/form/div[5]/div/button</value>
      <webElementGuid>97e90cd2-06d6-4e8f-9c2c-270054742cea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='política de privacidad'])[1]/following::button[1]</value>
      <webElementGuid>fc8cb6f8-1942-41d8-8c4e-ffa6533bd06b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tu e-mail'])[1]/following::button[1]</value>
      <webElementGuid>7d8b5453-6f32-4ae6-b074-02a7811d912e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dirección de instalación'])[1]/preceding::button[1]</value>
      <webElementGuid>559d06f1-7717-4d88-8a8e-839a5d63dced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datos de pago y confirmación'])[1]/preceding::button[1]</value>
      <webElementGuid>0d7fa282-639a-4823-a718-0efb463f7525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirmar']/parent::*</value>
      <webElementGuid>2df375b7-46f2-4d05-bbf2-588c1dd455a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/button</value>
      <webElementGuid>4361d522-4b8c-421d-9bd1-f39e98ae3539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Confirmar' or . = 'Confirmar')]</value>
      <webElementGuid>77489f45-1bf6-4c87-b84b-917e2ac3e311</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
