<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Provincia_city</name>
   <tag></tag>
   <elementGuidId>1c8d51a8-27ab-49e1-93ea-83596b3c95de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='city']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;city&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5d974027-d84f-4033-a955-8069b4f18e23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>90674bf1-991b-4515-85bd-c59fb01ec798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout-step-header-2&quot;)/div[@class=&quot;checkout-step_body__EMYJI&quot;]/section[@class=&quot;checkout-steps_form_2__d1nZe&quot;]/form[@class=&quot;form_form__DAL4d&quot;]/div[@class=&quot;jsx-3227251525&quot;]/div[1]/label[@class=&quot;input_outlined__As810&quot;]/input[1]</value>
      <webElementGuid>9e2d4e9d-4277-40df-af51-605045bffccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1ce2be7-cc14-43ab-8c01-3935057504d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>755c3012-1eb1-4a03-8e58-93321eabfa5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout-step-header-2&quot;)/div[@class=&quot;checkout-step_body__EMYJI&quot;]/section[@class=&quot;checkout-steps_form_2__d1nZe&quot;]/form[@class=&quot;form_form__DAL4d&quot;]/div[@class=&quot;jsx-3227251525&quot;]/div[1]/label[@class=&quot;input_outlined__As810&quot;]/input[1]</value>
      <webElementGuid>7eb64b1e-07f0-4487-8e26-48c8df359bd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='city']</value>
      <webElementGuid>70b779fd-9119-49e4-a163-066be60520c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-step-header-2']/div[2]/section/form/div[8]/div/label/input</value>
      <webElementGuid>904b0c7e-3c91-4209-aa03-ae40a7a32f46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/label/input</value>
      <webElementGuid>be04ec7a-3e4a-40fe-935b-cbc63bab357e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'city']</value>
      <webElementGuid>c1aea863-d1cb-4ac8-be86-ca12a00c2afd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
