<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cdigo postal_province</name>
   <tag></tag>
   <elementGuidId>f0bfa986-bafa-4cd5-a16c-ce91f249ae40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='province']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;province&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b37d7c1e-d5c3-4dd0-8ae4-8cef30f8983c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkout-steps_province__qd2U_</value>
      <webElementGuid>e52559f5-dd0f-473e-8643-1f5fc267e6ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>province</value>
      <webElementGuid>2adcddc6-017d-438b-bfce-989159bef3e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout-step-header-2&quot;)/div[@class=&quot;checkout-step_body__EMYJI&quot;]/section[@class=&quot;checkout-steps_form_2__d1nZe&quot;]/form[@class=&quot;form_form__DAL4d&quot;]/div[@class=&quot;jsx-3227251525 checkout-steps_province__qd2U_&quot;]/div[1]/label[@class=&quot;input_outlined__As810&quot;]/input[@class=&quot;checkout-steps_province__qd2U_&quot;]</value>
      <webElementGuid>8801c711-0d33-4b2d-ad0d-5e0e1016a8ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b28e0e4-cb2f-4552-b98c-710d9ce58ff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkout-steps_province__qd2U_</value>
      <webElementGuid>0efdb715-74e4-4f1f-8172-fa850096919e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>province</value>
      <webElementGuid>8637984d-114d-48b2-803b-3322217bd81a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout-step-header-2&quot;)/div[@class=&quot;checkout-step_body__EMYJI&quot;]/section[@class=&quot;checkout-steps_form_2__d1nZe&quot;]/form[@class=&quot;form_form__DAL4d&quot;]/div[@class=&quot;jsx-3227251525 checkout-steps_province__qd2U_&quot;]/div[1]/label[@class=&quot;input_outlined__As810&quot;]/input[@class=&quot;checkout-steps_province__qd2U_&quot;]</value>
      <webElementGuid>b042f84b-677d-4de2-80bb-43b08d7352b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='province']</value>
      <webElementGuid>8125edbf-e1f7-48b7-8e8e-ba3479de397f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-step-header-2']/div[2]/section/form/div[7]/div/label/input</value>
      <webElementGuid>a613e698-d1b9-405e-bbbc-6b106bd9f352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/label/input</value>
      <webElementGuid>ed59cff0-6a0a-481f-8ffd-aa81d6054516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'province']</value>
      <webElementGuid>e4263dfe-c688-44bf-979f-52db807bd537</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
