<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tipo de documento_docNumber</name>
   <tag></tag>
   <elementGuidId>09b1ce6d-c4f9-4490-bd59-391a434ffa5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='docNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;docNumber&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a23104a1-857d-4eed-8818-ba054a052216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkout-steps_docNumber__kWJAo</value>
      <webElementGuid>b1686dc7-8a3e-4619-beff-2c3dcfe0d25d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>docNumber</value>
      <webElementGuid>cb82a8ee-f3d1-4116-96cb-3d5504b5f471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout-step-header-2&quot;)/div[@class=&quot;checkout-step_body__EMYJI&quot;]/section[@class=&quot;checkout-steps_form_2__d1nZe&quot;]/form[@class=&quot;form_form__DAL4d&quot;]/div[@class=&quot;jsx-3227251525 checkout-steps_docNumber__kWJAo&quot;]/div[1]/label[@class=&quot;input_outlined__As810&quot;]/input[@class=&quot;checkout-steps_docNumber__kWJAo&quot;]</value>
      <webElementGuid>a31b0388-396b-47a6-8a5e-2143c604ecb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e5baefa-8484-4a65-9458-c3c967e49e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkout-steps_docNumber__kWJAo</value>
      <webElementGuid>a275629e-e4b6-4c40-9efb-a42327adf482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>docNumber</value>
      <webElementGuid>a85e04de-f1c9-4b3b-8b58-db2fa4c4fff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout-step-header-2&quot;)/div[@class=&quot;checkout-step_body__EMYJI&quot;]/section[@class=&quot;checkout-steps_form_2__d1nZe&quot;]/form[@class=&quot;form_form__DAL4d&quot;]/div[@class=&quot;jsx-3227251525 checkout-steps_docNumber__kWJAo&quot;]/div[1]/label[@class=&quot;input_outlined__As810&quot;]/input[@class=&quot;checkout-steps_docNumber__kWJAo&quot;]</value>
      <webElementGuid>d9ee148b-ac60-4407-833a-fdad744bd74e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='docNumber']</value>
      <webElementGuid>a122a6d8-ff46-446f-b76b-657856cdd0e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-step-header-2']/div[2]/section/form/div[2]/div/label/input</value>
      <webElementGuid>b17c6d4e-26c8-40b6-8bc1-5393ff7020a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4e480f21-9a42-4ec1-b1e0-761fa64c879a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'docNumber']</value>
      <webElementGuid>4e475f0e-6aaa-4942-9fc6-6a2378c46a29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
