<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nombre y apellidos_phone</name>
   <tag></tag>
   <elementGuidId>1b1a5c69-652e-4d90-8f76-010d895f5f9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='phone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;phone&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b38f749a-b25b-43e3-9a3e-6bef539873d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkout-steps_phone__b2Jxh</value>
      <webElementGuid>a95d5b6a-79ca-48bd-86ba-962d20228fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>baa28bb0-d741-4f0e-bdc5-9db988c0357c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout-step-header-1&quot;)/div[@class=&quot;checkout-step_body__EMYJI&quot;]/section[@class=&quot;checkout-steps_form_1__RQPYl&quot;]/form[@class=&quot;form_form__DAL4d&quot;]/div[@class=&quot;jsx-3227251525 checkout-steps_phone__b2Jxh&quot;]/div[1]/label[@class=&quot;input_outlined__As810&quot;]/input[@class=&quot;checkout-steps_phone__b2Jxh&quot;]</value>
      <webElementGuid>763fe2ab-d282-4833-b1bd-e15e37ff18e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5855fa1b-5c4c-4162-b592-af8a85eefa39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkout-steps_phone__b2Jxh</value>
      <webElementGuid>adecc1d4-2248-4e85-94e8-246d3e6f47ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>4717e7cd-11f5-4da7-bf0b-ad5dd9bd0852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout-step-header-1&quot;)/div[@class=&quot;checkout-step_body__EMYJI&quot;]/section[@class=&quot;checkout-steps_form_1__RQPYl&quot;]/form[@class=&quot;form_form__DAL4d&quot;]/div[@class=&quot;jsx-3227251525 checkout-steps_phone__b2Jxh&quot;]/div[1]/label[@class=&quot;input_outlined__As810&quot;]/input[@class=&quot;checkout-steps_phone__b2Jxh&quot;]</value>
      <webElementGuid>42df2e51-2aa1-4f15-98a6-20e0525b1185</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='phone']</value>
      <webElementGuid>79b1ac6d-9c1d-487c-b5d5-ec9f7604ceda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-step-header-1']/div[2]/section/form/div[2]/div/label/input</value>
      <webElementGuid>7287ab54-7a16-4376-bec8-7085fd0d14e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label/input</value>
      <webElementGuid>7fe04753-7588-4d70-86d9-69b033815acc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'phone']</value>
      <webElementGuid>c7bf883d-2b73-4d74-9e2c-591d2fe36336</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
