<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Localidad</name>
   <tag></tag>
   <elementGuidId>daa543cb-3438-4075-8c26-afbba290996d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='checkout-step-header-2']/div[2]/section/form/div[8]/div/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ceeeba93-62ce-42f5-8afa-0d08a736c856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Localidad</value>
      <webElementGuid>9fa028de-78f8-4ffd-bc05-eea09dbac65d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout-step-header-2&quot;)/div[@class=&quot;checkout-step_body__EMYJI&quot;]/section[@class=&quot;checkout-steps_form_2__d1nZe&quot;]/form[@class=&quot;form_form__DAL4d&quot;]/div[@class=&quot;jsx-3227251525&quot;]/div[1]/label[@class=&quot;input_outlined__As810&quot;]/span[1]</value>
      <webElementGuid>6ae1145b-da5b-47f5-b552-0a0a76b13b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e84a2b95-f3d9-409d-8b1a-775e39f28576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Localidad</value>
      <webElementGuid>5e7f2bcb-93eb-408b-bf32-543a174d1d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout-step-header-2&quot;)/div[@class=&quot;checkout-step_body__EMYJI&quot;]/section[@class=&quot;checkout-steps_form_2__d1nZe&quot;]/form[@class=&quot;form_form__DAL4d&quot;]/div[@class=&quot;jsx-3227251525&quot;]/div[1]/label[@class=&quot;input_outlined__As810&quot;]/span[1]</value>
      <webElementGuid>0a128941-6aea-4ddc-878c-ff34495d5270</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-step-header-2']/div[2]/section/form/div[8]/div/label/span</value>
      <webElementGuid>d9c7ced0-d8b1-42aa-b67e-f05d48c9e27f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provincia'])[1]/following::span[1]</value>
      <webElementGuid>9aaa4aa1-59a3-476a-bd7a-0169133def86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Código postal'])[1]/following::span[2]</value>
      <webElementGuid>c7ebbc9a-be21-4a3c-8d10-fd515fdfab95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de vía'])[1]/preceding::span[1]</value>
      <webElementGuid>b50590c2-4783-4c7b-928b-c1b4a22585b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nombre de la vía'])[1]/preceding::span[2]</value>
      <webElementGuid>7eb9c3b9-90b1-4aa8-95f8-9d224d575fd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Localidad']/parent::*</value>
      <webElementGuid>73ede903-b395-460b-bb5e-9ad15dac3e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/label/span</value>
      <webElementGuid>721e74d9-5a4a-4303-9222-0be5ac156d23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Localidad' or . = 'Localidad')]</value>
      <webElementGuid>a06e01cb-ce70-4128-a162-df8414ab6cda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
